### ISSUE TITLE
Informative messages in home page

### ISSUE THREAD

**Issue by Berat-Dzhevdetov** [Berat-Dzhevdetov/DeemZ-Platform#17] opened 2021-09-17 18:59 UTC
Let's make a table for headings and use the table from the database of informative messages. The new table will be so that we can divide them into different sections, and the table of informative messages will contain things like text, display period and such.

**Comment by Berat-Dzhevdetov** [comment] 2021-09-17 19:02
We can also add priority to sections

**Comment by Boyan-Apostolov** [comment] 2021-09-18 14:17
And also remove the notification if user is already enrolled

**Comment by Berat-Dzhevdetov** [comment] 2021-09-22 18:53
Тhe functionality is ready! There is only one problem left that I can't think of a solution to. I will be happy for you to help me. When I pull from the database the messages that should be displayed are displayed and those that should not.

**Comment by Boyan-Apostolov** [comment] 2021-09-24 19:11
The problem is solved, if you have the nerves, you can also create a custom map for the AutoMapper:)
_If you consider this as a good fix, close the issue_

**Closed as completed** 2021-10-02 06:26 UTC
Labels: new feature
